[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 2
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
